"""add construction safety incidents

Revision ID: 28a1caa54cd6
Revises: 6834dbb496e1
Create Date: 2026-03-12 23:20:18.453975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a1caa54cd6'
down_revision: Union[str, None] = '6834dbb496e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_safety_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.Enum('near_miss', 'minor_injury', 'major_injury', 'property_damage', 'environmental', 'fire', 'other', name='incident_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_on_site', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('injured_person_name', sa.String(length=255), nullable=True),
    sa.Column('time_lost_days', sa.Integer(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_actions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('reported', 'under_investigation', 'corrective_action_pending', 'closed', name='incident_status'), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['construction_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('construction_safety_incidents')
    # ### end Alembic commands ###
