"""add construction budget lines

Revision ID: 6834dbb496e1
Revises: 00ff574b2498
Create Date: 2026-03-12 23:17:12.177407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6834dbb496e1'
down_revision: Union[str, None] = '00ff574b2498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('labor', 'materials', 'equipment', 'subcontractors', 'overhead', 'contingency', 'other', name='budget_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['construction_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('construction_budget_lines')
    # ### end Alembic commands ###
