"""add_construction_equipment

Revision ID: eea65bfce79b
Revises: 3191e74dc248
Create Date: 2026-03-12 23:37:58.140310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea65bfce79b'
down_revision: Union[str, None] = '3191e74dc248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('heavy_machinery', 'lifting', 'earthmoving', 'compaction', 'concrete', 'electrical', 'scaffolding', 'safety', 'survey', 'other', name='equipment_category'), nullable=False),
    sa.Column('status', sa.Enum('available', 'in_use', 'under_maintenance', 'out_of_service', 'returned', name='equipment_status'), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('rental_rate_daily', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mobilization_date', sa.Date(), nullable=True),
    sa.Column('demobilization_date', sa.Date(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['construction_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('construction_equipment')
    # ### end Alembic commands ###
